### ISSUE TITLE
Dont work

### ISSUE THREAD

**Issue by crpmax** [Prunt/AutoAFK#3]
Hi, the plugin does not recognize whatever or not is the player moving or doing something. It puts players in AFK mode, while they normally move, fly, teleport, type commands.

**Comment by crpmax** [comment]
https://youtu.be/vaW1-PIUL60

**Comment by hankur** [comment]
Could you post your config here? It seems that you don't have required listeners enabled.

**Comment by crpmax** [comment]
https://hastebin.com/odevuvutuk.php

**Comment by hankur** [comment]
Try changing `listeners.move` to `true`.

**Comment by crpmax** [comment]
No change

**Comment by hankur** [comment]
Okay, found the bug. It's fixed in the next version.
