### ISSUE TITLE
AFK players are invincible...

### ISSUE THREAD

**Issue by TechnoRunner18** [Prunt/AutoAFK#4]
I am having a problem with the damage protection setting. If protection.damage is set to false, players in afk mode are invincible. Even if i negate the autoafk.protection.damage permission, players in afk mode cannot be harmed. No one has any bypass or /god perms (no OPs). How is this possible?

When players are in afk mode, I still want them to take damage from entities and players...

**Comment by hankur** [comment]
If you give (not negate) the "autoafk.protection.damage" permission, it should work. But yes, config option was broken.
